name: Build OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y build-essential git wget unzip python3 python3-distutils libncurses5-dev libz-dev gawk flex quilt

      - name: Download OpenWrt source code
        run: |
          git clone --depth 1 https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure OpenWrt
        run: |
          cd openwrt
          cp ../diffconfig ./.config
          make defconfig

      - name: Build OpenWrt
        run: |
          cd openwrt
          make -j$(nproc)

      - name: Upload firmware
        run: |
          cd openwrt/bin/targets/x86/64
          ls -l
          echo "::set-output name=firmware_file::$(ls openwrt-*-combined-squashfs.img.gz)"
        id: find_firmware

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: openwrt/bin/targets/x86/64/${{ steps.find_firmware.outputs.firmware_file }}
          tag_name: ${{ github.run_id }}
          name: OpenWrt Firmware Build ${{ github.run_id }}
