# Target settings
TARGET_ARCH="x86"
TARGET_ARCH_PACKAGES="x86_64"
TARGET_SUBTARGET="generic"
TARGET_VARIANT="generic"

# LuCI settings
CONFIG_LUCI=y
CONFIG_LUCI_LANG_ZH_CN=y

# Network settings
CONFIG_PACKAGE_kmod-iwlwifi=y
CONFIG_PACKAGE_kmod-iwlwifi- Intel-I226=y

# Software package settings
CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_TARGET_KERNEL_PARTSIZE=64
CONFIG_TARGET_ROOTFS_PARTSIZE=2048

# Additional packages
CONFIG_PACKAGE_passwall=y
CONFIG_PACKAGE_homeproxy=y
CONFIG_PACKAGE_dockerman=y

# Other settings
CONFIG_BUILD_LOG=y
CONFIG_BUILD_SOURCE=y
CONFIG_CLEAN_UP=y
CONFIG_CHECK_ERRORS=y
CONFIG_DOWNLOAD_FOLDER="/tmp/openwrt-dl"
CONFIG_TARGET_OPTIMIZATION="-Os -pipe -march=x86-64 -mtune=generic"
